### ISSUE TITLE
image input from STDIN not working

### ISSUE THREAD

**Issue by marado** [larsjsol/shellpic#10]
shellpic -h says:
 positional arguments:
   image              Use '-' to read from STDIN

However, while `shellpic image.jpg` works as intended, `cat image.jpg|shellpic -` (which should be the same thing, but the image is not being piped to shellpic's STDIN, and the - argument is being given to make it work) fails:

Traceback (most recent call last):
  File "/usr/local/bin/shellpic", line 109, in <module>
    main()
  File "/usr/local/bin/shellpic", line 61, in main
    anim = Animation(args.image, args.animate or args.loop)
  File "/usr/local/lib/python3.4/dist-packages/shellpic/animation.py", line 31, in __init__
    img = Image.open(filename)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2251, in open
    fp = builtins.open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '-'

**Comment by larsjsol** [comment]
It seems like support for reading from stdin disappeared some time ago. It's back in v1.6.2.

Thanks for letting me know!
